#### Vector
- 1D array

#### Data Frame
- vectors of multiple types,
- Must have same length like spread sheet

##### List 
- Ordered

#### The numeric data

In [1]:
# get a numeric data type
n1 <- 15
n1

[1] 15

In [2]:
typeof(n1)

[1] "double"

In [3]:
n2 <- 1.5
n2

[1] 1.5

In [4]:
typeof(n2)

[1] "double"

#### The character

In [5]:
c1 <- "c"
c1

[1] "c"

In [6]:
typeof(c1)

[1] "character"

In [7]:
c2<-"a string of text"
c2
typeof(c2)

[1] "a string of text"

[1] "character"

#### The logical data

In [9]:
l1 <- TRUE
l1
typeof(l1)

[1] TRUE

[1] "logical"

In [10]:
l2 <- F
l2
typeof(l2)

[1] FALSE

[1] "logical"

#### The vector

In [11]:
v1 <- c(1,2,3,4,5)
v1
is.vector(v1)

[1] 1 2 3 4 5

[1] TRUE

In [13]:
v2 <- c("a","b","c")
v2
is.vector(v2)

[1] "a" "b" "c"

[1] TRUE

In [14]:
v3 <- c(T,T,F,F,T)
v3
is.vector(v3)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] TRUE

##### The matrix

In [16]:
m1 <- matrix(c(T,T,F,F,T,F), nrow = 2)
m1


[,1] [,2]  [,3] 
[1,] TRUE FALSE  TRUE
[2,] TRUE FALSE FALSE

In [19]:
m2 <- matrix(c("a","b","c","d"), nrow = 2, byrow = T)
m2

[,1] [,2]
[1,] a    b   
[2,] c    d

#### Array

In [23]:
a1 <- array( c(1:24), c(4,3,2) ) # row , col , quantity
a1

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

#### Dataframe data type

In [34]:
vNumveric <- c(1,2,3)
vCharacter <- c("a","b","c")
vLogical <- c(T,F,T)

dfa <- cbind(vNumveric, vCharacter, vLogical)
dfa
typeof(dfa)

df <- as.data.frame(cbind(vNumveric, vCharacter, vLogical))
df
typeof(df)

vNumveric vCharacter vLogical
[1,] 1         a          TRUE    
[2,] 2         b          FALSE   
[3,] 3         c          TRUE

[1] "character"

vNumveric vCharacter vLogical
1 1         a          TRUE    
2 2         b          FALSE   
3 3         c          TRUE

[1] "list"

In [35]:
o1 <- c(1,2,3)
o2 <- c("a","b","c","d")
o3 <- c(T,F,T,T,F)

list1 <- list(o1, o2, o3)
list1

[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1]  TRUE FALSE  TRUE  TRUE FALSE

#### COERCING TYPE LIKE CASTING

In [37]:
(coerce1 <- c(1,"b",TRUE))
typeof(coerce)

[1] "1"    "b"    "TRUE"

[1] "closure"

In [38]:
# change to integer

coerce2 <- 5
typeof(coerce2)

(coerce3 <- as.integer(5))
typeof(coerce3)

[1] "double"

[1] 5

[1] "integer"

In [41]:
# convert the matrix into dataframe
(coerce6 <- matrix(1:9, nrow = 3))
is.matrix(coerce6)

(coerce7 <- as.data.frame(matrix(1:9, nrow=3)))
is.data.frame(coerce7)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] TRUE

V1 V2 V3
1 1  4  7 
2 2  5  8 
3 3  6  9

[1] TRUE